config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :customers do
    root to: "homes#top"
    get '/search' => 'searches#search'
    get "about" => "homes#about"
    get "orders/new" => "orders#new"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :create]
    resources :products, only: [:show, :index]
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :update, :destroy, :create]

    resource "customers", only: [:show, :edit, :update]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
  end

 devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  namespace :admins do
    root to: "homes#top"
    get "search" => 'searches#search'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [ :show, :update] do
      patch "admins/order_products/:id" => "order_products#update", as: "order_product"
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  
  has_many :cart_products, dependent: :destroy
  
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  
  
  
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  

  
  # is_valid==falseの場合、ログインさせない
  def active_for_authentication?
    super && (is_valid?)
  end
  
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_products, dependent: :destroy
    
    
    #enumを用いて、番号で扱えるようにしている
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    
    enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admins_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_valid)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_products = @order.order_products
    if @order.status == "入金確認"
      @order_products.each do |order_product|
        order_product.status = "製作待ち"
        order_product.save
      end
    end
    redirect_to admins_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/customers/cart_products_controller.rb
class Customers::CartProductsController < ApplicationController

  def index
    @cart_products = CartProduct.all
  end

  def update
    @cart_product = CartProduct.find(params[:id])
    @cart_product.update(cart_product_params)
    redirect_to cart_products_path
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_products_path
  end

  def destroy_all
    @cart_products = current_customer.cart_products
    @cart_products.destroy_all
    redirect_to cart_products_path
  end

  def create
    @cart_product = current_customer.cart_products.new(cart_product_params)
    @cart_product.save
    redirect_to cart_products_path
  end

  private
  def cart_product_params
    params.require(:cart_product).permit(:product_id, :customer_id, :amount)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
    
def show
    @customer = current_customer
end

def edit
    @customer = current_customer
end

def update
    @customer = current_customer
    if @customer.update(customer_params)
        redirect_to customers_path
    else
        render :edit
    end
end


def unsubscribe
    @customer = current_customer
end

def withdraw
    @customer = current_customer
    @customer.update(is_valid: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
end



private

def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postcode, :phone_number)
end

end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

  def top
    @products = Product.all
  end

  def about
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController

    
    def index
        #最新の注文から並べるために.reverse_orderを使用している
        @orders = current_customer.orders.page(params[:page]).per(8).reverse_order
    end
    
    
    def thanks
    end
    
    def new
        @order = Order.new
        @address = current_customer.address
        @shipping_address_new = ShippingAddress.new
        @shipping_addresses = current_customer.shipping_addresses
    end
    
    
    #newページから情報を取得して、confirmページ上に情報を書き出すための記述
    def confirm
        @cart_products = current_customer.cart_products
        @order = Order.new(order_params)
        @order.shipping_fee = 800
        @order.payment_method = params[:order][:payment_method]
        
        #ラジオボタンで選択した時の取得する情報の条件分岐、enumではなくnew.html.erbで0,1,2を振り分けている
        if params[:order][:address_num] == "0"
            @order.postcode = current_customer.postcode
            @order.address = current_customer.address
            @order.name = current_customer.last_name + current_customer.first_name
        elsif params[:order][:address_num] == "1"
            #f.selectのaddress_boxの中の/:id の番号を取得する
            @shipping_address = ShippingAddress.find(params[:order][:address_box])
            @order.postcode = @shipping_address.postcode
            @order.address = @shipping_address.address
            @order.name = @shipping_address.name
            
        elsif params[:order][:address_num] == "2"
            @order.postcode = params[:order][:postcode]
            @order.address = params[:order][:address]
            @order.name = params[:order][:name]
        end
        
    end
    
    def show
        @order = Order.find(params[:id])
        @order_products = @order.order_products
    end
    
    #confirmページで注文を確定するを押した後の動作を記述してる
    def create
        #order_paramsで取得できる情報の保存
        order = Order.new(order_params)
        order.status = 0
        order.customer_id = current_customer.id
        order.save
        
        #商品情報の保存
        cart_products = current_customer.cart_products
        cart_products.each do |item|
            order_product = OrderProduct.new
            order_product.order_id = order.id
            order_product.product_id = item.product.id
            order_product.amount = item.amount
            order_product.price = item.sub_price
            order_product.status = 0
            order_product.save
        end

        current_customer.cart_products.destroy_all
        
        
        unless Customer.where(id: order.customer_id).where(postcode: order.postcode).where(address: order.address) || ShippingAddress.where(customer_id: order.customer_id).where(name: order.name).where(postcode: order.postcode).where(address: order.address).exits?                                       
            shipping_address = ShippingAddress.new
            shipping_address.customer_id = order.customer_id
            shipping_address.name = order.name
            shipping_address.postcode = order.postcode
            shipping_address.address = order.address
            shipping_address.save
        end
        redirect_to orders_thanks_path
    end
    
    private
    
    def order_params
        params.require(:order).permit(:payment_method, :postcode, :address, :name, :bill, :shipping_fee, :status, :customer_id)
    end
    
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  
  def index
    @products = Product.all.page(params[:page]).per(8)
  end
  
  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
  end
  
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/searches_controller.rb
class Customers::SearchesController < ApplicationController
  def search
    @product = Product.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def reject_inactive_user
    @customer = Customer.find_by(name: params[:customer][:first_name])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_valid
        redirect_to root_path
      end
    end
  end
  
  
  
end

app/controllers/customers/shipping_addresses_controller.rb
class Customers::ShippingAddressesController < ApplicationController
    
def index
    @shipping_address_new = ShippingAddress.new
    @shipping_addresses = current_customer.shipping_addresses
end

def create
    @shipping_address_new = ShippingAddress.new(shipping_params)
    @shipping_address_new.customer_id = current_customer.id
    if @shipping_address_new.save
       redirect_to shipping_addresses_path
    else
       @shipping_addresses = current_customer.shipping_addresses
       render :index
    end
end

def edit
    @shipping_address = ShippingAddress.find(params[:id])
end

def update
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.update(shipping_params)
    redirect_to shipping_addresses_path
end


def destroy
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    redirect_to shipping_addresses_path
end

private

def shipping_params
    params.require(:shipping_address).permit(:name, :postcode, :address)
end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customer/cart_products_helper.rb
module Customer::CartProductsHelper
end

app/views/customers/orders/confirm.html.erb
<body>
  <div class="container">
    <div class="row">
      
          <h4 class="mb-4 text-color col-3 text-center ml-5 pb-2 pt-2 rounded-pill">注文情報確認</h4>
    </div> 
        
          <div class="row">
            <table class="table table-bordered border-dark col-7">
            <thead>
              <tr class="table-color">
                  <th class="table-active">商品名</th>
                  <th class="table-active">単価(税込)</th>
                  <th class="table-active">数量</th>
                  <th class="table-active">小計</th>
              </tr>
            </thead>
            <tbody>
              <% @sum = 0 %>
              <% @cart_products.each do |cart_product| %>
              <tr>
                  <td><%= cart_product.product.name  %></td>
                  <td><%= cart_product.product.add_tax_price %></td>
                  <td><%= cart_product.amount %></td>
                  <td><%= cart_product.product.add_tax_price * cart_product.amount %></td>
              </tr>
              <% @sum += cart_product.product.add_tax_price * cart_product.amount %>
              <% end %>
            </tbody>
           </table>

           <table class="table table-bordered border-dark col-2 mb-3 ml-5 h-75">
              <tr>
                  <th class="table-active">送料</th>
                  <td><%= @order.shipping_fee %></td>
              </tr>
              <tr>
                  <th class="table-active table-color">商品合計</th>
                  <td><%= @sum %></td>
              </tr>
              <tr>
                  <th class="table-active">請求金額</th>
                  <td><%= @order.shipping_fee + @sum %></td>
              </tr>
           </table>
        </div>
        
        

          <div class="payment_info row mt-3 mb-3">
              <h5 class="font-weight-bold">支払方法　　</h5>
              <%= @order.payment_method %>
              <br>
          </div>

          <div class="address_info row mb-3">
              <h5 class="font-weight-bold">お届け先　　</h5>
              <span>〒</span><%= @order.postcode %>　<%= @order.address %><br><%= @order.name %>
              <br>
          </div>
          
          
          
      <div class="row">
        
        <div class="col-5 confirm_image"></div>
        <div class="col-6">
        <%= form_with model:@order, url: orders_path, local:true do |f| %>
        
        
        <%= f.hidden_field :payment_method %>
        <%= f.hidden_field :postcode %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :shipping_fee %>
        <%= f.hidden_field :bill, value: @sum + @order.shipping_fee %>
        
          
          <br> <br><br><br> <%= f.submit "➡︎注文を確定する", class: "btn btn-primary col-5" %>
          </div>

        <% end %>
      </div>  
  </div>
</body>

app/views/customers/orders/index.html.erb
<body>
  <div class="container">
    <div class="row">
      
          <h4 class="mb-4 text-color col-3 text-center  pt-4 rounded-pill">注文履歴一覧</h4>
          <div class="col-7 order_index_image offset-1"></div>
      
    </div>
    <div class="row">
      <div class="col">
          <table class="table table-bordered border-dark col-12 mt-3 mb-5">
              <tr class="table-color">
                  <th class="table-active">注文日</th>
                  <th class="table-active">配送先</th>
                  <th class="table-active">注文商品</th>
                  <th class="table-active">支払い金額</th>
                  <th class="table-active">ステータス</th>
                  <th class="table-active">注文詳細</th>
              </tr>
              <% @orders.each do |order| %>
              <tr>
                  <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                  <td><%= order.postcode %><br><%= order.address %><br><%= order.name %></td>
                  <td>
                      <% order.order_products.each do |order_product| %>
                      <%= order_product.product.name %>
                      <% end %>
                  </td>
                  <td><%= order.bill.to_s(:delimited) %>円</td>
                  <td><%= order.status %></td>
                  <td><%= link_to "表示する", order_path(order) ,class: "btn btn-primary btn-sm" %></td>
              </tr>
              <% end %>
          </table>
          <%= paginate @orders %>
      </div>
    </div>
  </div>
</body>

app/views/customers/orders/new.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-7">
          <h4 class="mb-4 text-color col-4 text-center ml-5 pb-2 pt-2 rounded-pill">注文情報入力</h4>


          <%= form_with(model:@order, url: orders_confirm_path, local: true) do |f| %>
          <div class="field">
            <span class="font-weight-bold">支払い方法</span><br>

            <div class="form-check mt-3">
                <%= f.radio_button :payment_method,:クレジットカード,  checked: "checked" %>
                <%= f.label :payment_method, "クレジットカード" %>
                <br>
                <%= f.radio_button :payment_method, :銀行振込 %>
                <%= f.label :payment_method, "銀行振込" %>
            </div>
          </div>


          <div class="field">
            <span class="font-weight-bold">お届け先</span><br>

            <div class="form-check mt-3">
                <%= f.radio_button :address_num,0,  checked: "checked" %>
                <%= f.label :address, "ご自身の住所" %>
                <p class="ml-3"><%= @address %></p>

                <%= f.radio_button :address_num, 1 %>
                <%= f.label :address, "選択済み住所から選択" %>
                <p class="ml-3"><%= f.select :address_box, options_for_select(@shipping_addresses.map do |ship|
                     ["〒" + ship.postcode + "  " + ship.address + "  " + ship.name , ship.id]end) %></p>

                <%= f.radio_button :address_num,2 %>
                <%= f.label :address, "新しいお届け先" %>
                  <div class="field mb-1">
                    <%= f.label :"郵便番号(ハイフンなし)", class: 'col-4' %>
                    <%= f.text_field :postcode, autofocus: true, class: 'rounded', placeholder: "0000000" %>
                  </div>
                  <div class="field mb-1">
                    <%= f.label :"住所", class: 'col-4' %>
                    <%= f.text_field :address, autofocus: true, class: 'rounded col-6', placeholder: "東京都渋谷区代々木神園町0-0" %>
                  </div>
                  <div class="field mb-1">
                    <%= f.label :"宛名", class: 'col-4' %>
                    <%= f.text_field :name, autofocus: true, class: 'rounded', placeholder: "令和道子" %>
                  </div>
            </div>
          </div>

          <div class="row justify-content-center">
            <%= f.submit "確認画面へ進む", class: "btn btn-primary col-3" %>
          </div>


          <% end %>

      </div>
      
      <div class="col-5 order_new_image">
      </div>
      
      
      
    </div>
  </div>
</body>

app/views/customers/orders/show.html.erb
<body>
  <div class="container">

    <div class="row mb-3">
      
        <h4 class="mb-4 text-color col-md-3 text-center pt-4 rounded-pill">注文履歴詳細</h4>
        <div class="col-7 order_show_image offset-1"></div>

    </div>
          <div class="row">
            <div class="col-7"><p class="font-weight-bold">注文情報</p></div>
            <div class="col-3"><p class="font-weight-bold ml-3">請求情報</p></div>
          <table class="table table-bordered border-dark col-7">

                  <tr>
                      <th class="table-active table-color col-3">注文日</th>
                      <th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">配送先</th>
                    <th><%= @order.postcode %><br><%= @order.address %><br><%= @order.name %></th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">支払い方法</th>
                    <th><%= @order.payment_method %></th>
                  </tr><tr>
                    <th class="table-active table-color">ステータス</th>
                    <th><%= @order.status %></th>
                  </tr>
          </table>
          <table class="table table-bordered border-dark col-3 ml-3 h-75">
                  <tr>
                      <th class="table-active table-color">表品合計</th>
                      <th><%= @order.bill - @order.shipping_fee %>円</th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">配送料</th>
                    <th><%= @order.shipping_fee %>円</th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">ご請求額</th>
                    <th><%= @order.bill %>円</th>
                  </tr>
          </table>
          </div>
          
          <div class="row"><p class="font-weight-bold table-color">注文内容</p></div>
          <table class="table table-bordered border-dark col-9 mt-3 mb-5">
              <tr class="table-color">
                  <th class="table-active  col-6">商品</th>
                  <th class="table-active">単価（税込）</th>
                  <th class="table-active">個数</th>
                  <th class="table-active">小計</th>
              </tr>
              <% @order_products.each do |order_product| %>
              <tr>
                  <th><%= order_product.product.name %></th>
                  <th><%= order_product.product.add_tax_price %>円</th>
                  <th><%= order_product.amount %>個</th>
                  <th><%= order_product.product.add_tax_price * order_product.amount %>円</th>
              </tr>
              <% end %>
          </table>
      </div>
    </div>
  </div>
</body>

app/views/customers/orders/thanks.html.erb
<div class = "container">
  <div class = "row">
    <div class="px-3 mx-auto  mt-5">
       
        <h3 style="text-align:center">
          ご注文ありがとうございました!!
        </h3>
     </div>
     <div class="thanks_image offset-2" style="height: 400px;"></div>
    </div>
  </div>
  <div class="row mb-5">
     <div class="col-12 text-align-center">
       　　　　　　<%= link_to "注文履歴見る!!", orders_path, class:'btn btn-primary ml-5 ' %> 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 <%= link_to "Topページへ", root_path, class:'btn btn-primary ml-5 offset-5' %>
     </div>
  </div>
</div>