config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :customers do
    root to: "homes#top"
    get '/search' => 'searches#search'
    get "about" => "homes#about"
    get "orders/new" => "orders#new"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :create]
    resources :products, only: [:show, :index]
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :update, :destroy, :create]

    resource "customers", only: [:show, :edit, :update]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
  end

 devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  namespace :admins do
    root to: "homes#top"
    get "search" => 'searches#search'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [ :show, :update] do
      patch "admins/order_products/:id" => "order_products#update", as: "order_product"
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  
  belongs_to :customer
  belongs_to :product
  
  #商品の税込価格を出すメソッド
  def add_tax_price
    (self.product.price * 1.10).round
  end
  
  #商品毎の合計金額を出すメソッド
  def sub_price
      add_tax_price * self.amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  
  has_many :cart_products, dependent: :destroy
  
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  
  
  
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  

  
  # is_valid==falseの場合、ログインさせない
  def active_for_authentication?
    super && (is_valid?)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_products, dependent: :destroy
    
    
    #enumを用いて、番号で扱えるようにしている
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    
    enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product

    enum status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image
  has_many :cart_products, dependent: :destroy
  belongs_to :genre
  has_many :order_products, dependent: :destroy


  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
  end


end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :customer
    
   
    validates :postcode, presence: true
    validates :address, presence: true
    validates :name, presence: true
end

app/controllers/admins/searches_controller.rb
class Admins::SearchesController < ApplicationController
  def search
    @products = Product.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
        admin_root_path
    when Customer
        customers_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postcode, :phone_number])
  end
  
end

app/controllers/customers/searches_controller.rb
class Customers::SearchesController < ApplicationController
  def search
    @product = Product.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/admins/searches_helper.rb
module Admins::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/helpers/customers/searches_helper.rb
module Customers::SearchesHelper
end

app/views/admins/searches/search.html.erb
<script src="https://kit.fontawesome.com/8a2ca55f79.js" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">

<div class="guide-plate d-flex align-items-center justify-content-center">
  <div class=admin-page-title>商品一覧</div>
</div>

<div class="admin-products-cover1 d-flex align-items-center justify-content-center">
  <div class="admin-products-cover2 d-flex align-items-center justify-content-center">
    <div class="overflow-auto" style="width:100%; height:500px">
      <div class="container">
        <div class="row">
          <%= link_to new_admins_product_path do %>
            <i class="fas fa-plus-circle fa-3x new-button"></i>
          <% end %>
          <table class='table table-borderless'>
            <thead>
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><%= product.id %></td>
                  <td><%= link_to product.name, admins_product_path(product.id) %></td>
                  <td><%= product.price %></td>
                  <td><%= product.genre.name %></td>
                  <td>
                  <% if product.status == true %>
                    <p class="text-success">販売中</p>
                  <% else %>
                    <p class="text-secondary">販売停止中</p>
                  <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
　　　  </div>
　　　</div>
    </div>
  </div>
</div>