config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :customers do
    root to: "homes#top"
    get '/search' => 'searches#search'
    get "about" => "homes#about"
    get "orders/new" => "orders#new"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:index, :show, :create]
    resources :products, only: [:show, :index]
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :update, :destroy, :create]

    resource "customers", only: [:show, :edit, :update]

    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
  end

 devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  namespace :admins do
    root to: "homes#top"
    get "search" => 'searches#search'
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [ :show, :update] do
      patch "admins/order_products/:id" => "order_products#update", as: "order_product"
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_products, dependent: :destroy
    
    
    #enumを用いて、番号で扱えるようにしている
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    
    enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_products = @order.order_products
    if @order.status == "入金確認"
      @order_products.each do |order_product|
        order_product.status = "製作待ち"
        order_product.save
      end
    end
    redirect_to admins_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController

    
    def index
        #最新の注文から並べるために.reverse_orderを使用している
        @orders = current_customer.orders.page(params[:page]).per(8).reverse_order
    end
    
    
    def thanks
    end
    
    def new
        @order = Order.new
        @address = current_customer.address
        @shipping_address_new = ShippingAddress.new
        @shipping_addresses = current_customer.shipping_addresses
    end
    
    
    #newページから情報を取得して、confirmページ上に情報を書き出すための記述
    def confirm
        @cart_products = current_customer.cart_products
        @order = Order.new(order_params)
        @order.shipping_fee = 800
        @order.payment_method = params[:order][:payment_method]
        
        #ラジオボタンで選択した時の取得する情報の条件分岐、enumではなくnew.html.erbで0,1,2を振り分けている
        if params[:order][:address_num] == "0"
            @order.postcode = current_customer.postcode
            @order.address = current_customer.address
            @order.name = current_customer.last_name + current_customer.first_name
        elsif params[:order][:address_num] == "1"
            #f.selectのaddress_boxの中の/:id の番号を取得する
            @shipping_address = ShippingAddress.find(params[:order][:address_box])
            @order.postcode = @shipping_address.postcode
            @order.address = @shipping_address.address
            @order.name = @shipping_address.name
            
        elsif params[:order][:address_num] == "2"
            @order.postcode = params[:order][:postcode]
            @order.address = params[:order][:address]
            @order.name = params[:order][:name]
        end
        
    end
    
    def show
        @order = Order.find(params[:id])
        @order_products = @order.order_products
    end
    
    #confirmページで注文を確定するを押した後の動作を記述してる
    def create
        #order_paramsで取得できる情報の保存
        order = Order.new(order_params)
        order.status = 0
        order.customer_id = current_customer.id
        order.save
        
        #商品情報の保存
        cart_products = current_customer.cart_products
        cart_products.each do |item|
            order_product = OrderProduct.new
            order_product.order_id = order.id
            order_product.product_id = item.product.id
            order_product.amount = item.amount
            order_product.price = item.sub_price
            order_product.status = 0
            order_product.save
        end

        current_customer.cart_products.destroy_all
        
        
        unless Customer.where(id: order.customer_id).where(postcode: order.postcode).where(address: order.address) || ShippingAddress.where(customer_id: order.customer_id).where(name: order.name).where(postcode: order.postcode).where(address: order.address).exits?                                       
            shipping_address = ShippingAddress.new
            shipping_address.customer_id = order.customer_id
            shipping_address.name = order.name
            shipping_address.postcode = order.postcode
            shipping_address.address = order.address
            shipping_address.save
        end
        redirect_to orders_thanks_path
    end
    
    private
    
    def order_params
        params.require(:order).permit(:payment_method, :postcode, :address, :name, :bill, :shipping_fee, :status, :customer_id)
    end
    
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="admin-heading col-md-12">
      <h3 class="mb-4 col-3 pt-2 pb-2">注文履歴詳細</h3>
    </div>
    <table class="table table-sm mb-3 admin-order-show-table">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to "#{@order.customer.last_name} #{@order.customer.first_name}", admins_customer_path(@order.customer.id), class: "text-dark border-bottom border-dark" %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admins_order_path(@order), local: true do |f| %>
              <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"]], class: "form-control" %>
              <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row mb-5">
    <div class="col-7">
      <table class="table mt-3 table-borderless table-hover rounded-top rounded-bottom table_border_radius admin-order-table">
        <thead class="thead-dark">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @order_products.each do |order_product| %>
          <tr>
            <td><%= order_product.product.name %></td>
            <td><%= order_product.product.add_tax_price %></td>
            <td><%= order_product.amount %></td>
            <td>
              <% @products_price = order_product.product.add_tax_price * order_product.amount %>
              <%= @products_price %>
            </td>
            <td>
              <%= form_with model: order_product, url: admins_order_order_product_path(@order, order_product), local: true do |f| %>
                <%= f.select :status, [["着手不可", "着手不可"], ["製作待ち", "製作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
              <% end %>
            </td>
            <% @sum += @products_price %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @sum %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td>800円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @sum + 800 %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>